default: &default
  adapter: postgresql
  timeout: 5000
  username: matthewkr
  password:
  pool: 5
  # encoding: unicode

development:
  <<: *default
  host: localhost
  database: conteu_development3

test:
  <<: *default
  host: localhost
  database: conteu_test3

staging:
  # encoding: utf8

production:
  # encoding: utf8
