default: &default
  adapter: postgresql
  timeout: 5000
  username: matthewkrog
  password:
  pool: 5
  # encoding: unicode

development:
  <<: *default
  host: localhost
  database: conteu_development

test: &test
  <<: *default
  host: localhost
  database: conteu_test

staging:
  # encoding: utf8

production:
  # encoding: utf8

cucumber:
  <<: *test
